"""Spec-grounded agent test generation."""

from .input_compiler import InputContractError, compile_input_file, compile_test_input
from .fixture_materializer import (
    FixtureMaterializationError,
    materialize_fixture_bundle,
    materialize_fixture_file,
)
from .candidate_generator import (
    CandidateGenerationError,
    generate_candidate_bundle,
    generate_candidate_files,
)
from .compiler import (
    ArtifactBundleError,
    ArtifactSchemaRegistration,
    CompilerRequestError,
    SourceContractError,
    SourceAnchorLoadError,
    TargetCellSelectionError,
    compile_request_file,
    compile_test_plan,
    artifact_capability_status,
    artifact_document_for_capability,
    artifact_for_capability,
    artifact_identity_view,
    artifacts_for_capability,
    make_resolved_spec_target,
    make_source_spec_record,
    make_source_spec_record_v2,
    load_source_spec_record,
    resolve_artifact_bundle_file,
    resolve_source_spec_target,
    select_target_cells,
    source_record_columns,
    source_record_metadata,
    validate_resolved_spec_target,
    validate_accepted_artifact_catalog,
    validate_selected_spec_ref,
    validate_source_spec_record,
    validate_selected_coverage_target,
)

__all__ = [
    "FixtureMaterializationError",
    "CandidateGenerationError",
    "InputContractError",
    "ArtifactBundleError",
    "ArtifactSchemaRegistration",
    "CompilerRequestError",
    "SourceContractError",
    "SourceAnchorLoadError",
    "TargetCellSelectionError",
    "compile_input_file",
    "compile_test_input",
    "compile_request_file",
    "compile_test_plan",
    "artifact_capability_status",
    "artifact_document_for_capability",
    "artifact_for_capability",
    "artifact_identity_view",
    "artifacts_for_capability",
    "make_resolved_spec_target",
    "make_source_spec_record",
    "make_source_spec_record_v2",
    "load_source_spec_record",
    "resolve_artifact_bundle_file",
    "resolve_source_spec_target",
    "select_target_cells",
    "source_record_columns",
    "source_record_metadata",
    "validate_resolved_spec_target",
    "validate_accepted_artifact_catalog",
    "validate_selected_spec_ref",
    "validate_source_spec_record",
    "validate_selected_coverage_target",
    "materialize_fixture_bundle",
    "materialize_fixture_file",
    "generate_candidate_bundle",
    "generate_candidate_files",
]
